{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  cfg = config.features.cli.yazi;
in
{
  options.features.cli.yazi.enable = lib.mkEnableOption "yazi file manager";

  config = lib.mkIf cfg.enable {
    programs.yazi = {
      enable = true;
      package = inputs.yazi.packages.${pkgs.stdenv.hostPlatform.system}.default;

      # Adds the `y` wrapper: quit with q to cd into the browsed directory
      enableZshIntegration = true;
      shellWrapperName = "y";

      # yazi.toml
      settings = {
        mgr = {
          ratio = [
            1
            4
            3
          ];
          sort_by = "natural";
          sort_dir_first = true;
          show_hidden = true;
          show_symlink = true;
        };
        preview = {
          tab_size = 2;
          max_width = 1000;
          max_height = 1000;
        };
      };

      # keymap.toml
      keymap = {
        mgr.prepend_keymap = [
          {
            on = "!";
            run = ''shell "$SHELL" --block'';
            desc = "Open a shell here, exit to return to yazi";
          }
        ];
      };

      # theme.toml is generated by stylix (tokyo-night), no manual theme here
    };
  };
}
